import Login from "@/components/layouts/Login";
import React from "react";

export const metadata = {
  title: "Login - Forum Amikom",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const Page = () => {
  return <Login />;
};

export default Page;
