export const metadata = {
  title: "Beranda - Forum Amikom",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

import Home from "@/components/layouts/Home";
export default function Page() {
  return <Home />;
}
